version: '3'
services:
  web_page_fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["ruby", "main.rb", "https://www.google.com", "https://www.autify.com"]
